- src/hardware/encoder.cpp
I made the final calculation more static as suggested by Infineon. Seems to work according to spec now.
The problem is however that the angle speed register stores the angle change since the last measurement. Because the TLE5012 takes around 24k measurements every second, this change is very small, so a precise value is likely only possible with high RPM or by calculating the average over many samples. I don't think that the STM32 can handle 24k readings per second plus all the other stuff, so that will always be just an estimation.
Another interesting register is the angle revolution register, which counts full revolutions of the motor. This could be used to track absolute motor position without having to count revolutions in software.
> Fixed getEncoderSpeed function

- .vscode/settings.json
- src/hardware/buttons.cpp
- src/hardware/oled.cpp
- src/hardware/oled.h
- src/user/config.h
- src/user/main.cpp
OLED was redone on the backend for ease of understanding. Warnings were also added as a feature.
> OLED renaming merge

- src/hardware/flash.cpp
- src/hardware/motor.cpp
- src/hardware/timers.cpp
- src/software/fastSine.cpp
- src/software/fastSine.h
- src/user/config.h
Use SINE_VAL_COUNT as a power of 2.
> Save a little time in fastSin() and fastCos()

- README.md
- src/hardware/canMessaging.cpp
- src/hardware/flash.cpp
- src/hardware/flash.h
- src/hardware/motor.cpp
- src/hardware/motor.h
- src/hardware/oled.cpp
- src/hardware/oled.h
- src/hardware/serial.cpp
- src/hardware/timers.cpp
- src/hardware/timers.h
- src/software/fastSine.cpp
- src/software/fastSine.h
- src/software/parser.cpp
- src/software/parser.h
- src/user/config.h
- src/user/main.cpp
- src/user/main.h
- Save, load, and wipe parameters from flash
- OLED saved flash parameter options
- Minor fix to stepper reversal logic
- Automatic loading of parameters at startup
- Minor adjustment to how menu code works to allow possible later scaling option
- Additional firmware features to capability printout
- Minor speed increase in sin() and cos() functions
> Flash Management Features (dev -> master)

- platformio.ini
- src/hardware/buttons.cpp
- src/hardware/canMessaging.h
- src/hardware/flash.cpp
- src/hardware/motor.cpp
- src/hardware/motor.h
- src/hardware/oled.cpp
- src/hardware/timers.cpp
- src/user/config.h
- src/user/main.cpp
Includes 'Stepping-Speed-Improvements'.
47kHz stepping rate
> Stepping Speed Improvements - Part 3

- software/sineTableGenerator.py
> Sine table generator

- src/user/cube.cpp
- src/user/main.cpp
When SystemClock_Config_HSE_8M_SYSCLK_128M() is selected
PLLCLK is 128kHz
> Measure PLLCLK on MCO 

- src/hardware/motor.cpp
- src/hardware/motor.h
- src/user/config.h
Commenting of 
```
if (current == 0) {
desiredState = IDLE_MODE;
}
```
allow speed up to  55kHz under SystemClock_Config_HSE_8M_SYSCLK_72M()
> Speedup to 55kHz

- README.md
- src/hardware/motor.cpp
- src/hardware/timers.cpp
- src/software/fastAnalogWrite.cpp
- src/user/config.h
140kHz measured in origin BTT board.
See https://github.com/CAP1Sup/Intellistep/issues/39
> Reduce motor noise: Set MOTOR_PWM_FREQ to 140kHz

- src/user/config.h
> Reduce motor noise: Set motor PWM 139.5kHz and 9bit resolution

- src/software/MovingAverage.h
Hi, Chistian.
Do not take it for nagging on my part.
Don't take this as nit-picking on my part.
See single commits in order for a simple understanding of the train of thought.
Thanks.
> Moving average: review the code

- src/software/MovingAverage.h
Win/remove one subtraction in code.
Unfortunately not much.
That's all.
> Moving average: review the code 2

- src/hardware/timers.cpp
- src/user/config.h
- src/user/main.cpp
> Check encoder speed

- src/hardware/encoder.cpp
- src/hardware/encoder.h
The idea of this PR is to use integer MovingAverage for raw encoder data and convert it to float at the last moment.
Ready to merge
> Use integer MovingAverage to encoder Angle funcctions

- src/hardware/serial.cpp
- src/user/config.h
Serial doesn't work without setTx(), setRx()
> Serial.setTx() Serial.setRx()

- README.md
- src/hardware/motor.cpp
- src/hardware/motor.h
- src/hardware/timers.cpp
- src/hardware/timers.h
- src/software/parser.cpp
- src/user/config.h
- src/user/main.cpp
TIM2 is now set up as a hardware step counter. This ensures that there are no missed steps.
> Feature merge from TIM2 Master Record

- src/hardware/encoder.cpp
- src/hardware/encoder.h
- src/hardware/flash.cpp
- src/hardware/motor.cpp
- src/hardware/motor.h
- src/hardware/oled.cpp
- src/software/macros.h
- src/user/config.h
I have separated the encoder and the estimation velocity of motor.
Estimation velocity is the best choice.
0RPM
375RPM
> Split the encoder and estimation velocity of motor

- src/config/config.h
- src/config/config_adv.h
- src/hardware/flash.cpp
- src/hardware/motor.cpp
- src/hardware/motor.h
- src/software/fastSine.cpp
- src/software/sanityCheck.h
Probably, a separate branch will be more convenient.
> Step-dir under ideal conditions

- src/hardware/buttons.cpp
Reduce the length of function to one monitor screen.
> Reduce IF code

- src/main/main.cpp
The motor has a small jump(move) after being powered on.
> Zero the encoder after the motor is enabled
